import Link from "next/link";
import { ArrowUpRight, CalendarDays, Ticket, WandSparkles } from "lucide-react";

export default function Home() {
  return (
    <main className="min-h-screen overflow-hidden bg-[#0b0f19] text-slate-100">
      <nav className="mx-auto flex max-w-6xl items-center justify-between px-5 py-6"><Link href="/" className="heading-font text-xl font-semibold text-white">Event<span className="text-blue-400">Sphere</span></Link><div className="flex items-center gap-3"><Link href="/attendee" className="rounded-lg px-3 py-2 text-sm text-slate-300 hover:text-white">Explore</Link><Link href="/event" className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-500">Create event <ArrowUpRight className="ml-1 inline h-4 w-4" /></Link></div></nav>
      <section className="mx-auto grid max-w-6xl gap-12 px-5 pb-20 pt-16 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:pt-24"><div><p className="tech-label text-blue-400">Events, with intent</p><h1 className="heading-font mt-5 max-w-3xl text-6xl font-bold leading-[0.98] tracking-tight text-white sm:text-7xl">Make room for the moments that matter.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-400">A focused workspace for discovering, publishing, selling, and running remarkable events from first idea to final check-in.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/attendee" className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-500">Find your next event <ArrowUpRight className="ml-2 inline h-4 w-4" /></Link><Link href="/dashboard" className="rounded-xl border border-slate-700 px-5 py-3 text-sm font-semibold text-slate-200 hover:border-blue-400">Open dashboard</Link></div></div><div className="relative rounded-[2rem] border border-slate-800 bg-[#131926] p-6 shadow-2xl shadow-blue-950/30"><div className="absolute -right-8 -top-8 h-32 w-32 rounded-full bg-blue-500/10 blur-2xl" /><p className="text-xs uppercase tracking-[0.2em] text-slate-500">One platform, three rhythms</p><div className="mt-8 space-y-4">{[[CalendarDays, "Shape the experience", "Agenda, speakers, venue, and ticket tiers in one place."], [Ticket, "Move people through", "Multi-ticket checkout, QR tickets, and event-day check-in."], [WandSparkles, "Make it smarter", "Recommendations, description drafts, and schedule suggestions."]].map(([Icon, title, body]) => <div key={String(title)} className="flex gap-4 border-t border-slate-800 pt-4"><Icon className="mt-1 h-5 w-5 shrink-0 text-blue-400" /><div><h2 className="font-semibold text-white">{String(title)}</h2><p className="mt-1 text-sm leading-6 text-slate-400">{String(body)}</p></div></div>)}</div></div></section>
      <section className="border-t border-slate-800/80 bg-[#101622]"><div className="mx-auto grid max-w-6xl gap-6 px-5 py-12 text-sm text-slate-400 sm:grid-cols-3"><p><strong className="block text-white">Discover</strong>Filter by city, category, date, and price.</p><p><strong className="block text-white">Run</strong>Live attendance counts and downloadable lists.</p><p><strong className="block text-white">Connect</strong>Reviews, reminders, wishlist, and networking.</p></div></section>
    </main>
  );
}
