import Link from "next/link";
import { ArrowUpRight, CalendarDays, Ticket, WandSparkles } from "lucide-react";

export default function Home() {
  return (
    <main className="min-h-screen overflow-hidden bg-[#0b0f19] text-slate-100">
      <section className="mx-auto grid max-w-6xl gap-12 px-5 pb-20 pt-16 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:pt-24"><div><p className="tech-label text-blue-400">Your event workspace</p><h1 className="heading-font mt-5 max-w-3xl text-6xl font-bold leading-[0.98] tracking-tight text-white sm:text-7xl">Discover, host, and run events.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-400">Choose where you want to start. EventSphere keeps tickets, people, schedules, and event-day operations in one place.</p><div className="mt-9 grid gap-3 sm:grid-cols-2"><Link href="/attendee" className="rounded-2xl bg-blue-600 p-5 text-white shadow-lg shadow-blue-600/20 hover:bg-blue-500"><Ticket className="h-6 w-6" /><strong className="mt-5 block text-lg">I’m attending</strong><span className="mt-1 block text-sm text-blue-100">Browse events, save tickets, and meet attendees <ArrowUpRight className="ml-1 inline h-4 w-4" /></span></Link><Link href="/auth?role=organiser&next=%2Fevent" className="rounded-2xl border border-slate-700 bg-[#131926] p-5 text-white hover:border-blue-400"><CalendarDays className="h-6 w-6 text-blue-400" /><strong className="mt-5 block text-lg">I’m organizing</strong><span className="mt-1 block text-sm text-slate-400">Sign in to create an event, sell tickets, and manage check-in <ArrowUpRight className="ml-1 inline h-4 w-4" /></span></Link></div><Link href="/auth" className="mt-5 inline-block text-sm font-semibold text-blue-300">Sign in or create an account to continue →</Link></div><div className="relative rounded-[2rem] border border-slate-800 bg-[#131926] p-6 shadow-2xl shadow-blue-950/30"><div className="absolute -right-8 -top-8 h-32 w-32 rounded-full bg-blue-500/10 blur-2xl" /><p className="text-xs uppercase tracking-[0.2em] text-slate-500">Everything connected</p><div className="mt-8 space-y-4">{[[CalendarDays, "Shape the experience", "Agenda, speakers, venue, and ticket tiers."], [Ticket, "Move people through", "Checkout, QR tickets, refunds, and check-in."], [WandSparkles, "Make it smarter", "Recommendations, descriptions, and schedule ideas."]].map(([Icon, title, body]) => <div key={String(title)} className="flex gap-4 border-t border-slate-800 pt-4"><Icon className="mt-1 h-5 w-5 shrink-0 text-blue-400" /><div><h2 className="font-semibold text-white">{String(title)}</h2><p className="mt-1 text-sm leading-6 text-slate-400">{String(body)}</p></div></div>)}</div></div></section>
      <section className="border-t border-slate-800/80 bg-[#101622]"><div className="mx-auto grid max-w-6xl gap-6 px-5 py-12 text-sm text-slate-400 sm:grid-cols-3"><p><strong className="block text-white">Discover</strong>Filter by city, category, date, and price.</p><p><strong className="block text-white">Run</strong>Live attendance counts and downloadable lists.</p><p><strong className="block text-white">Connect</strong>Reviews, reminders, wishlist, and networking.</p></div></section>
    </main>
  );
}
