"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { loginUser, registerUser } from "@/lib/eventApi";

export default function AuthPage() {
  const [mode, setMode] = useState<"login" | "register">("login");
  const [form, setForm] = useState({ name: "", email: "", password: "", role: "attendee" });
  const [message, setMessage] = useState("");
  useEffect(() => { const params = new URLSearchParams(window.location.search); if (params.get("role") === "organiser") setForm((current) => ({ ...current, role: "organiser" })); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { const data = mode === "login" ? await loginUser({ email: form.email, password: form.password }) : await registerUser(form); localStorage.setItem("eventsphere-token", data.token); localStorage.setItem("eventsphere-user", JSON.stringify(data.user)); const next = new URLSearchParams(window.location.search).get("next"); window.location.href = next || (data.user.role === "organiser" ? "/event" : "/attendee"); } catch (error: any) { setMessage(error.message); } };
  return <main className="flex min-h-screen items-center justify-center bg-[#0b0f19] px-4 text-slate-100"><form onSubmit={submit} className="w-full max-w-md rounded-2xl border border-slate-800 bg-[#131926] p-7"><Link href="/" className="text-sm text-blue-300">← EventSphere</Link><h1 className="heading-font mt-7 text-4xl font-bold text-white">{mode === "login" ? "Welcome back" : "Create your account"}</h1><p className="mt-2 text-sm text-slate-400">Your identity unlocks organizer tools, tickets, and networking.</p>{mode === "register" ? <input required placeholder="Full name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="mt-6 w-full rounded-lg border border-slate-700 bg-[#182032] px-3 py-3 text-sm text-white" /> : null}<input required type="email" placeholder="Email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="mt-3 w-full rounded-lg border border-slate-700 bg-[#182032] px-3 py-3 text-sm text-white" /><input required minLength={6} type="password" placeholder="Password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} className="mt-3 w-full rounded-lg border border-slate-700 bg-[#182032] px-3 py-3 text-sm text-white" />{mode === "register" ? <select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} className="mt-3 w-full rounded-lg border border-slate-700 bg-[#182032] px-3 py-3 text-sm text-white"><option value="attendee">Attendee</option><option value="organiser">Organiser</option></select> : null}<button className="mt-5 w-full rounded-xl bg-blue-600 py-3 text-sm font-semibold text-white">{mode === "login" ? "Log in" : "Create account"}</button>{message ? <p className="mt-3 text-sm text-rose-300">{message}</p> : null}<button type="button" onClick={() => setMode(mode === "login" ? "register" : "login")} className="mt-5 text-sm text-blue-300">{mode === "login" ? "Need an account? Register" : "Already registered? Log in"}</button></form></main>;
}
